sudo: false

language: cpp

cache:
  pip: true

addons:
  apt:
    packages:
      - python2.7-pyroot

python:
  - "2.7"

branches:
    only:
      - master
      - develop

git:
  depth: 1

install:
  - pip install -r requirements.txt

script:
  - for test in tests/*.py; do python ${test}; done

notifications:
  email: false
