sudo: false

language: python

cache:
  pip: true

addons:
  apt:
    packages:
      - python2.7-pyroot

python:
  - "2.7"

branches:
    only:
      - master
      - develop

git:
  depth: 1

install:
  - pip install -r requirements.txt

script:
  - pytest
  - python tests/test_doc.py

notifications:
  email: false
