sudo: false

language: python

cache:
  pip: true
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/root

python:
  - "2.7"

branches:
    only:
      - master
      - develop

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake-3.6

git:
  depth: 1

install:
  - pip install -r requirements.txt
  - ROOT_DIR=${TRAVIS_BUILD_DIR}/deps/root
  - mkdir -p ${ROOT_DIR}
  - |
    if [[ -z "$(ls -A ${ROOT_DIR})" ]]; then
      URL="https://root.cern.ch/download/root_v6.10.02.source.tar.gz"
      { travis_retry wget --quiet -O - ${URL} | tar --strip-components=1 -xz -C ${ROOT_DIR}; } || exit 1
      (cd ${ROOT_DIR} && ./configure --minimal --enable-python --prefix=`pwd` && make install)
    fi
  - export PYTHONPATH=${ROOT_DIR/lib}:${PYTHONPATH}

script: pytest

notifications:
  email: false
