sudo: false

language: python

cache:
  pip: true

addons:
  apt:
    packages:
      - root-system
      - root-plugin-math-minuit2
      - python2.7-pyroot

python:
  - 2.7
  - 3.6

branches:
    only:
      - master
      - develop

git:
  depth: 1

install:
  - pip install pytest
  - python setup.py install

script:
  #- export PYTHONPATH=/usr/lib/x86_64-linux-gnu/root5.34:${PYTHONPATH}
  - pytest

notifications:
  email: false
