sudo: false

language: python

python:
  - "2.7"

branches:
    only:
      - master
      - develop

git:
  depth: 1

install:
  - pip install -r requirements.txt

script:
  - for test in tests/test_*.py; do python ${test}; done

notifications:
  email: false
